accuReport/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include("authenticator.urls")),
    path('', include('emergency.urls')),
]

authenticator/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.user_login, name='login'), 
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('logout', views.user_logout, name='logout'),
    path('index', views.index, name='index'),
    path('password-reset/<uidb64>/<token>', views.pwdReset, name='password-reset'),
    path('verifyMail', views.mailOTP, name='verifyMail'),
    path('createFile', views.create_file, name='createFile'),
]

emergency/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'emergency'
urlpatterns = [
    path('home', views.report_emergency, name='home'),
    path('alerts', views.accident_alerts, name='alerts'), 
    path('crimes', views.crime_alerts, name='crimes'),
    path('abstract', views.abstract, name='abstract'),
    path('chargesheet', views.charges, name='chargesheet'),
    path('medical', views.medical, name='medical'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticator/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models


class Officer(AbstractUser):
    police_number = models.CharField(max_length=10, unique=True)
    national_id = models.CharField(max_length=100, unique=True)

    groups = models.ManyToManyField(
        Group,
        related_name='officer_groups',  # Custom reverse accessor name
        blank=True,
        help_text='The groups this user belongs to. A user can belong to multiple groups. By default, users are assigned automatically to the "Registered users" group.',
        verbose_name='groups'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='officer_user_permissions',  # Custom reverse accessor name
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions'
    )

    is_superuser = models.BooleanField(
        default = False,
        help_text = 'Designates wether this users should have all permissions without explicitly assigning them',
        verbose_name = 'superuser status'
    )

    class Meta:
        unique_together = (("police_number", "national_id"),)





class AccidentFiles(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    abstract = models.CharField(max_length=1000, blank=True)  # Optional abstract field

    def __str__(self):
        return self.name 



class AccidentDraft(models.Model):
    scene = models.TextField()  # Use TextField for large text content
    created_date = models.DateTimeField(auto_now_add=True)  # Automatically record creation date

    def __str__(self):
        return f"Accident Draft - {self.created_date}"

authenticator/forms.py
from django.forms import ModelForm
from authenticator.models import AccidentFiles

class AccidentFileForm(ModelForm):
    class Meta:
        model = AccidentFiles
        fields = ['name', 'abstract']  # Include 'abstract' field

    def __init__(self, *args, **kwargs):
        super(AccidentFileForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages['required'] = 'Please enter a name for the accident file.'
        self.fields['abstract'].error_messages['required'] = 'Please enter a summary of the accident.'  # Add validation for abstract

authenticator/views.py
from django.urls import reverse
from django.utils.encoding import force_str, force_bytes #
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.shortcuts import redirect, render
from django.contrib import messages #Used for displaying the error messages on the html templates
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string #captures a html file with some text and then it will render it to text that will be dipsplayed to the user
from accuReport import settings
from authenticator.forms import AccidentFileForm
from authenticator.models import Officer
from django.contrib.auth import get_user_model
from django.contrib.messages import success
from django.contrib.messages import get_messages
from django.core.mail import EmailMessage, send_mail
from django.contrib.auth import logout
from django.contrib.auth import login as auth_login #it will be used inside the activate function so that it doesn't damage the default django login.
from django.db.models import Q 
from . tokens import generate_token
from django.http import HttpRequest
from .models import AccidentDraft, AccidentFiles
import json
from django.contrib.auth.tokens import default_token_generator



# Create your views here.



def signup(request):
    if request.method == "POST":
        # Get the data from the POST request
        firstname = request.POST.get("fname")
        lastname = request.POST.get("lname")
        userName = request.POST.get("userId")
        email = request.POST.get("email")
        nationalId = request.POST.get("idNo")
        policeNo = request.POST.get("policeNumber")
        password = request.POST.get("pwd")
        passwordRepeat = request.POST.get("pwdRepeat")

        # Before creating the user we have to autheticate the values entered

        try:
            officer = Officer.objects.create_user(username=userName, email=email, password=password)
         # Set additional fields
            officer.first_name = firstname
            officer.last_name = lastname
            officer.national_id = nationalId
            officer.police_number = policeNo
            #set hashed password
            officer.set_password(password)
            officer.is_active = False
            officer.save()
        except:
            if Officer.objects.filter(username=userName).exists():
                messages.error(request, "username already exist! Please try some other username",)
                return render(request,'authenticator/signup.html')
                
            
            if Officer.objects.filter(email=email).exists():
                messages.error(request, 'Email Already Registered')
                return render(request,'authenticator/signup.html')
                
            
            if Officer.objects.filter(police_number=policeNo).exists():
                messages.error(request, "Invalid police number, already registered.")
                return render(request,'authenticator/signup.html')
            

            if Officer.objects.filter(national_id = nationalId).exists() :
                messages.error(request, "Invalid national Id, already registered.")
                return render(request,'authenticator/signup.html')
                
            
            if not userName.isalnum():
                messages.error(request, "Invalid Username")
                return render(request,'authenticator/signup.html')
            
        #Create the user  only if the validation pass


        success(request, "Your Account created Successully.  We will send you an Email for Activation")
        #take him to the login page is the signup is successfull


        #Welcome confirmation mail
        subject = "Welcome to AccuReport."
        message = "Hello " + officer.first_name + "\n" + "Welcome to AccuReport! \nThank you for visiting our website, an automated way to handle accidents and crime reports\nWe have also sent you a confirmation email, please confirm that this is your email address. \n\nThank You\nTeamAccuReport"
        from_email = settings.EMAIL_HOST_USER
        to_list = [officer.email]
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        #email address confirmation Email
        current_site = get_current_site(request)
        email_subject = "Confirm your Email @  Accureport -Login"
        message2 = render_to_string("email_confirmation.html", {
            'name': officer.first_name,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(officer.pk)),
            'token': generate_token.make_token(officer)
        })

        email = EmailMessage(
            email_subject, 
            message2, 
            settings.EMAIL_HOST_USER, 
            [officer.email],
        )
        email.fail_silently = True
        email.send()
        return redirect('login')
    
    
    return render(request, "authenticator/signup.html")


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        officer = Officer.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Officer.DoesNotExist):
        officer = None
    
    if officer is not None and generate_token.check_token(officer, token):
        officer.is_active = True
        #User profile. signup confrirmation = Tru
        officer.save()
        auth_login(request,officer) #I encountered an error whereby I had two login functions login and login so I had to import as auth_login separately to handle the user authenitcation
        messages.success(request, 'Your account has been activated successfully')
        return redirect('login')
    else:
        return render(request, "activation_failed.html")





def user_login(request):
    #initialize messages before the conditional block

    msg = get_messages(request)
    if request.method == 'POST':
        identification = request.POST.get('credentials')
        password = request.POST.get("pwd")
        
  
        #Authentication with various fields
        officer = get_user_model()
        try:
            #fetch the users who match any of these fields
            officer = Officer.objects.get(Q(username=identification)  | Q(email=identification) | Q(police_number=identification))
            if officer.check_password(password):
                auth_login(request, officer)
                fname = officer.first_name + " " + officer.last_name
                request.session['fname'] = fname
                messages.success(request, "Welcome back " + fname)
                return redirect('index')    
            else:
                messages.error(request, "Incorrect password")
        except Officer.DoesNotExist:
            messages.error(request, "No such user.")
            return redirect('login')


   
        
    return render(request, "authenticator/login.html", {'messages': msg})





def index(request):
    # If 'fname' does not exist in session, redirect to login page
    if 'fname' not in request.session:
        return redirect('login')
    
    # Retrieve 'fname' from session
    fname = request.session['fname']
    
    return render(request, "authenticator/index.html", {'fname': fname})


def user_logout(request):
    logout(request)
    messages.success(request, "Logged Out")
    return redirect('login')


def create_accident_draft(request):
    if request.method == 'POST':
        scene = request.POST.get('scene')
        # Create a new AccidentDraft instance and save it
        accident_draft = AccidentDraft(scene=scene)
        accident_draft.save()
        # Redirect to a success page or display confirmation message
        messages.success(request, "Draft saved Successfully")  # Replace 'success_url' with your desired URL
    else:
        # Render the form for GET requests
        return render(request, 'accident_draft_form.html')



#function view for mail verification
# ... other imports


# ... other code


def mailOTP(request):
    if request.method == 'POST':
        userMail = request.POST.get('credentials')

        officer = get_user_model()

        try:
            officer = Officer.objects.get(Q(email=userMail))
        except Officer.DoesNotExist:
            messages.error(request, "Email does not exist.")
            return render(request, "authenticator/email_verification.html")

        current_site = get_current_site(request)
        subject = "Password Reset Request"
        message = render_to_string("pwd_reset_email.html", {
            'user': officer,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(officer.pk)),
            'token': default_token_generator.make_token(officer),
        })
        email = EmailMessage(subject, message, settings.EMAIL_HOST_USER, [officer.email])
        email.send()

        messages.success(request, "Password reset email sent.")

    return render(request, "authenticator/email_verification.html")


def pwdReset(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Officer.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Officer.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            new_password = request.POST.get("new_pwd")
            confirm_password = request.POST.get("pwdRepeat")

            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                messages.success(request, "Password reset successfully.")
                return redirect('login')
            else:
                messages.error(request, "Passwords do not match.")
        else:
            return render(request, "authenticator/password-reset.html")
    else:
        return render(request, "authenticator/reset_failed.html")

authenticator/templates/authenticator/body.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="css/login styles.css">
</head>
<body> 
    <h1 class="welcome">Welcome To <br> My Baby and Me</h1> 
    <div class="photo-grid">
        <div class="picture1">
            <img src="photos/momchild.jpg" alt="">
        </div>
        <div class="picture2">
            <img src="photos/baby orogami.jpg" alt="">
        </div>
        <div class="picture3">
            <img src="photos/mom.jpg" alt="">
        </div>
        <div class="picture4">
            <img src="photos/199d6c09025fed6a9f8f57f0d16501dc.jpg" alt="">
        </div>
        <div class="picture5">
            <img src="photos/646ee5ab2b22d0ff875bde5e187ca665.jpg" alt="">
        </div>
        <div class="picture6">
            <img src="photos/943845b0f8a7df539f629e49c3c40f4f.jpg" alt="">
        </div>
        <div class="picture7">
            <img src="photos/hand.jpg" alt="">
        </div>
        <div class="picture8">
            <img src="photos/login page.jpg" alt="">
        </div>
        <div class="picture9">
            <img src="photos/girl.jpg" alt="">
        </div>
        <div class="picture10">
            <img src="photos/family.jpg" alt="">
        </div>
    </div>

authenticator/templates/authenticator/create_file.html
{% include 'base.html' %}

{% include 'authenticator/navigation.html'%}



{% include 'footer.html' %}

authenticator/templates/authenticator/email_verification.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    <link rel="stylesheet" href="{% static 'css/logpage.css' %}">
</head>
<body>
    <div class="main">
            

        <div class="signin" style="border-radius: 10px">
            <div class="logelements">

                <h1>Email Verification</h1>
                <h3>Enter email used to register your account</h3>
                <form action="" method="post" id="emailVerification">
                    {% csrf_token %}
                    {% for message in messages %}
                    <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                    <label for="email">Enter your account email:  </label><br>
                    <input type="email" name="credentials" placeholder="user123@gmail.com" id="email"><br>            
                    <br>

                    <div id="errors"></div>
                    <br>
                    <button type="submit" name="login" style="width: 120pt; ">Recive OTP</button>

                </form>
                <br>
                Back to login page<a href="login">Login</a> <br>
            </div>
        </div>
</div>
<script>
const loginForm = document.getElementById( "emailVerification" );
const errorElement = document.getElementById('errors');

loginForm.addEventListener('submit', (event) => {
    //Prevent default submission which can cause double submission
    event.preventDefault();

    const email = document.getElementById('email').value;
  


    //Clear previos error messages
    errorElement.innerHTML = "";

    let messages =  [];

    function validateEmail(email) {
      var re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      return re.test(String(email).toLowerCase());//This will ensure the integrity of our database and the user won't be able to create an account if the email written is invalid
    }
    
        
    if(email == ""){
        messages.push("Field is empty, please enter an email.")
    }

    if (!validateEmail(email)){
      messages.push("Invalid email address");
    }




    if (messages.length === 0) {
        loginForm.disabled = true; // Disable form to prevent accidental resubmission
        setTimeout(() => {
        loginForm.submit(); // Submit the form after a short delay
        }, 1000); // Delay submission by 1 second
    } else {
        // Display error messages
        errorElement.innerHTML = messages.join(', ');
        errorElement.classList.add('error-message');
        errorElement.style.display = 'block';
        event.preventDefault(); // Prevent form submission
    }




});
</script>   
</body>
</html>


    
</body>
</html>

authenticator/templates/authenticator/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AccuReport-Login Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/logpage.css' %}">
</head>
<body> 

<div class="main">
            

        <div class="signin" style="border-radius: 10px">
            <div class="logelements">

                <h2>Glad You're Back</h2>
                <h1>Log In</h1>
                <form action="{% url 'login' %}" method="post" id="login-form">
                    {% csrf_token %}
                    {% for message in messages %}
                    <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                    <label for="email">Email Address/Username: </label><br>
                    <input type="text" name="credentials" placeholder="username'Pawi' or Email" id="details"><br>
                    <label for="password">Password</label><br>
                    <input type="password" name="pwd" id="pwd"><br>
                    <br>

                    <div id="errors"></div>
                    <br>
                    <button type="submit" name="login">Sign In</button>

                </form>
                <br>
                <a href="verifyMail">Forgot password?</a><br>
                First time here?<a href="signup">Create an account</a> <br>
            </div>
        </div>
</div>
<script>
const loginForm = document.getElementById( "login-form" );
const errorElement = document.getElementById('errors');

loginForm.addEventListener('submit', (event) => {
    const logInfo = document.getElementById('details').value;
    const password = document.getElementById('pwd').value;

    //Clear previous error messages
    errorElement.innerHTML = "";

    let messages =  [];

    if(logInfo == "" || password == ""){
        messages.push("Fields cannot be empty.")
    }

    if (messages.length > 0) {
        // Display error messages
        errorElement.innerHTML = messages.join(', ');
        errorElement.classList.add('error-message');
        errorElement.style.display = 'block';
        event.preventDefault(); // Prevent form submission
    }
});

</script>   
</body>
</html>

authenticator/templates/authenticator/navigation.html
<nav>
    <ul>
        <li><a href="/index">Menu</a></li>
        <li><a href="/home">Home</a></li>
        <li><a href="/">Community</a></li>
        <li><a href="/">About</a></li>
        <li><a href="/">Support</a></li>
        <li><a href="">Contact Us</a></li>
        <li id="profile" class="exclude"><div class="profile">{{ fname|slice:"0:1" }}</div></li>
        <li class="sesh_name"><a href="">{{ fname }}</a></li>
        <li id="logout" class="exclude"><a href="logout">LogOut</a></li>
    </ul>
</nav>

authenticator/templates/authenticator/password-reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    <link rel="stylesheet" href="{% static 'css/logpage.css' %}">
</head>
<body>
    <div class="main">
            

        <div class="signin" style="border-radius: 10px">
            <div class="logelements">

                <h1>Password Reset</h1>
                <h5>Create new Password</h5>
                <form action="" method="post" id="pwdReset">
                    {% csrf_token %}
                    {% for message in messages %}
                    <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                    <label for="pwd">Create New Password:</label><br>
                    <input type="password" name="new_pwd" id="pwd"><br>
                    <br>
                    <label for="pwdRepeat">Rewrite your New Password:</label><br>
                    <input type="password" name="pwdRepeat" id="pwdRepeat"><br>
                    <br>

                    <div id="errors"></div>
                    <br>
                    <button type="submit" name="reset" style="width: 120pt; ">Reset Password</button>

                </form>
                <br>
                Back to login page<a href="login">Login</a> <br>
            </div>
        </div>
</div>
<script>
const loginForm = document.getElementById( "pwdReset" );
const errorElement = document.getElementById('errors');

loginForm.addEventListener('submit', (event) => {
    //Prevent default submission which can cause double submission
    event.preventDefault();


    const password = document.getElementById('pwd').value;
    const passwordRepeat = document.getElementById('pwdRepeat').value;



    //Clear previos error messages
    errorElement.innerHTML = "";

    let messages =  [];


    if(password == "" || passwordRepeat == ""){
        messages.push("Fields cannot be empty.")
    }

    if (password !== passwordRepeat) {
        messages.push("Passwords don't match");
    }

    if (messages.length === 0) {
        loginForm.disabled = true; // Disable form to prevent accidental resubmission
        setTimeout(() => {
        loginForm.submit(); // Submit the form after a short delay
        }, 1000); // Delay submission by 1 second
    } else {
        // Display error messages
        errorElement.innerHTML = messages.join(', ');
        errorElement.classList.add('error-message');
        errorElement.style.display = 'block';
        event.preventDefault(); // Prevent form submission
    }




});
</script>   
</body>
</html>


    
</body>
</html>

authenticator/templates/authenticator/sidebar.html
<div class="side">
    <div class="logo"><img class="logos" src="{% static 'photos/Kenya_Police_Flag.gif' %}" alt="Kenya Police Flag">  <h3>The Kenya Police <br> <div class="motto">Utumishi Kwa Wote</div> </h3></div>
        <h2>ACCIDENT FILES</h2>
        <ul class="rec">
            <li id="abstractli"><a href="#" >Police Abstract</a></li>
            <li id="chargesheetli"><a href="chargesheet"  >Charge Sheet</a></li>
            <li id="medicalreportli"><a href="#" >Medical Examination Report</a></li>
        </ul>
        <h2>EMERGENCY ALERTS</h2>
        <ul class="dis">
            <li id="accidentAlertsli"><a href="{% url 'emergency:alerts' %}">Accident Alerts</a></li>
            <li><a href="">Crime Alerts</a></li>
        </ul>
        <h2>ACTION CENTER</h2>
        <ul class="cat">
            <li><a href="">Sketch Planning</a></li>
            <li><a href="">Progress Reports</a></li>
            <li><a href="">New Releases</a></li>
            <li><a href="">Upcoming</a></li>
            <li><a href="">Specials</a></li>
            <li><a href="">Virtual Reality</a></li>
            <li><a href="">Steam Controller</a></li>
        </ul>
        <h2>BROWSE BY GENRE</h2>
        <ul class="bro">
            <li><a href="">Free to Play</a></li>
            <li><a href="">Early Access</a></li>
            <li><a href="">Action</a></li>
            <li><a href="">Adventure</a></li>
            <li><a href="">Multiplayer Modes</a></li>
            <li><a href="">Sports</a></li>
            <li><a href="">Live action</a></li>
            <li><a href="">Classic Games</a></li>
        </ul>
</div>

authenticator/templates/authenticator/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AccuReport-SignUp</title> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/logpage.css' %}">
</head>
<body> 
<div class="container">

            
            <div id="step1">
                <div class="logelements">
                        <h2 class="head">Create an Account</h2>
                        <h1 >Sign Up</h1>


                        <form action="/signup" method="post" name="signupForm" id="signupForm">
                            {% csrf_token %}
                            {% for message in messages %}
                            <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                           
                            <label for="fname">Enter your first name:</label><br>
                            <input type="text" name="fname" id="fname" placeholder="Pawi"><br>
                            <p class="error fname-error"></p>
                    
                            <label for="lname">Enter your second name:</label><br>
                            <input type="text" name="lname" id="lname" placeholder="Fortune" ><br>
                            <p class="error lname-error"></p>

                            
                            <label for="userId">Enter a preferred User Name:</label><br>
                            <input type="text" name="userId" id="userId"><br>
                            <p class="error userId-error"></p>

                    
                            <label for="email">Email address:</label><br>
                            <input type="email" name="email" id="email" placeholder="user@example.com"><br>
                            <p class="error email-error"></p>
                    
                            <label for="idNo">National ID Number:</label><br>
                            <input type="text" name="idNo" id="idNo" placeholder="243434" ><br> 
                            <p class="error idNo-error"></p>
                            
                            <label for="policeNumber">Police Badge Number:</label><br>
                            <input type="text" name="policeNumber" id="policeNumber" placeholder="976543"><br>
                            <p class="error policeNo-error"></p>
   

                            <label for="pwd">Create Password:</label><br>
                            <input type="password" name="pwd" id="pwd"><br>
                            <p class="error pwd-error"></p>
    
                    
                            <label for="pwdRepeat">Rewrite your Password:</label><br>
                            <input type="password" name="pwdRepeat" id="pwdRepeat"><br>
                            <p class="error pwdRepeat-error"></p>
                            <br>


                           <div id="errors">

                           </div>
                            <br>

                    
                           
                    
                            <button type="submit" name="signup" id="signUp">Sign Up</button>
                        </form>
                        <br>
                    Already have an account? <a href="login">Sign In</a>
             </div>
               
                
            </div>
               <div class="signUp slideshow">
                <div class="motto">
                    <h1>Welcome to <a href="" class="name">AccuReport</a> , <br> a digital platform here to <br>
                        automate your reports</h1>
                </div>
  
            </div>
</div>
<script defer src="{% static 'js/script.js' %}"></script> 
 
</body>
</html>